# Generated by Django 3.2 on 2022-12-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailanime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeTitle', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('releasedDate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('otherNames', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=100)),
                ('animeImg', models.CharField(max_length=100)),
                ('totalEpisodes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topratedanime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeId', models.CharField(max_length=100)),
                ('animeTitle', models.CharField(max_length=100)),
                ('animeImg', models.CharField(max_length=100)),
                ('releasedDate', models.CharField(max_length=100)),
                ('animeUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
