# Generated by Django 3.2 on 2022-12-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_detailanime_topratedanime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topratedanime',
            old_name='releasedDate',
            new_name='latestEpisode',
        ),
    ]
