# Generated by Django 3.2 on 2022-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_rename_releaseddate_topratedanime_latestepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeId', models.CharField(max_length=100)),
                ('animeTitle', models.CharField(max_length=100)),
                ('animeImg', models.CharField(max_length=100)),
                ('releasedDate', models.CharField(max_length=100)),
                ('animeUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
