# Generated by Django 3.2 on 2022-12-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_remove_detailanime_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailanime',
            name='animeId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
